spring.mail.properties.mail.smtp.starttls.enable: true

spring:

  mail:
    host: ${EMAIL_SMTP_HOST}
    port: ${EMAIL_SMTP_PORT}
    username: ${NOTIFICATION_EMAIL_ADDRESS}
    password: ${NOTIFICATION_PASSWORD}
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE}
      idle-timeout: 1000
      pool-name: discapp_pool

    url: jdbc:postgresql://localhost:5432/discapp
    username: postgres
    password: password
    maxActive: ${DB_MAX_ACTIVE_CONNECTIONS}
    maxIdle: ${DB_MAX_IDLE_CONNECTIONS}
    removeAbandoned: true

  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true

logging:
  level:
    org:
      springframework:
        web: WARN
      hibernate:
      #SQL: DEBUG
      #type.descriptor.sql.BasicBinder: TRACE
    io:
      github:
        shamrice:
          discapp: ${DISCAPP_NOTIFIER_DEBUG_LEVEL}

server:
  port: 8082
  servlet:
    session:
      cookie:
        max-age: 14d
      timeout: 1d


discapp:
  manual-processing.enabled: ${MANUAL_PROCESSING_ENABLED}
  service-runner:
    sleep-duration: ${SERVICE_SLEEP_DURATION}
  email:
    base-url: ${BASE_URL}
    unsubscribe-url: ${UNSUBSCRIBE_URL_TEMPLATE}
    report-frequency.update.url: ${REPORT_FREQUENCY_UPDATE_URL}
    modify-account.url: ${MODIFY_ACCOUNT_URL}
    help-forum.url: ${HELP_FORUM_URL}
    maintenance:
      url: ${MAINTENANCE_URL}
      subscribers.url: ${MAINTENANCE_SUBSCRIBER_URL}
      stats.url: ${MAINTENANCE_STATS_URL}
      threads:
        url: ${MAINTENANCE_THREADS_URL}
        unapproved.url: ${MAINTENANCE_THREADS_UNAPPROVED_URL}
    admin:
      enabled: ${ADMIN_REPORT_ENABLED}
      send-hour: ${ADMIN_REPORT_SEND_HOUR}
      type: admin_report
    daily:
      enabled: ${DAILY_SUBSCRIPTION_ENABLED}
      send-hour: ${DAILY_SUBSCRIPTION_SEND_HOUR}
      type: daily_subscription
      subject: ${DAILY_SUBSCRIPTION_SUBJECT_TEMPLATE}
      thread-link-url: ${DAILY_SUBSCRIPTION_THREAD_LINK_TEMPLATE}
